TISklep/Controllers/FilmyController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using TISklep.DAL;
using TISklep.Models;
using TISklep.ViewModels;

namespace TISklep.Controllers
{
    public class FilmyController : Controller
    {
        FilmyContext db;
        IWebHostEnvironment hostEnvironment;
        public FilmyController(FilmyContext db, IWebHostEnvironment hostEnvironment)
        {
            this.db = db;
            this.hostEnvironment = hostEnvironment;
        }

        public IActionResult ListaFilmow(string nazwaKategorii)
        {
            KategoriaViewModel vm = new KategoriaViewModel(); 

            var kategoria = db.Kategorie.Include("Filmy").Where(k => k.Nazwa == nazwaKategorii).Single();
            var filmy = kategoria.Filmy.ToList();



            vm.FilmyKategorii = filmy;
            vm.Kategoria = kategoria;
            vm.FilmyTop3Najnowsze = db.Filmy.OrderByDescending(f => f.DataDodania).Take(3);

            return View(vm);
        }

        public IActionResult Szczegoly(int idFilmu)
        {
            var kategoira = db.Kategorie.Find(db.Filmy.Find(idFilmu).KategoriaId);
            var film = db.Filmy.Find(idFilmu);

            return View(film);
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Wszystkie()
        {
            var vm = db.Filmy.ToList();
            
            return View(vm);

        }
        [HttpGet]
        public IActionResult DodajFilm()
        {
            var model = new DodawanieFilmowViewModel();
            model.Kategorie = db.Kategorie.ToList();

            return View(model);
        }
        [HttpPost]
        public IActionResult DodajFilm(DodawanieFilmowViewModel obj)
        {
            obj.Film.DataDodania = DateTime.Now;

            var posterPath = Path.Combine(hostEnvironment.WebRootPath, "content");
            var posterName = Guid.NewGuid() + "_" + obj.Plakat.FileName;

            var filePath = Path.Combine(posterPath, posterName);
            obj.Plakat.CopyTo(new FileStream(filePath, FileMode.Create));

            obj.Film.Plakat = posterName;

            db.Filmy.Add(obj.Film);
            db.SaveChanges();

            return RedirectToAction("Wszystkie");
        }
        [HttpGet]
        public IActionResult EdytujFilm(int id)
        {
            var film = db.Filmy.Where(f => f.Id == id).FirstOrDefault();
            var kategoira = db.Kategorie.Find(db.Filmy.Find(id).KategoriaId);

            return View(film);
        }

        [HttpPost]
        public IActionResult EdytujFilm(Film film)
        {
            var edytowany = db.Filmy.Where(f => f.Id == film.Id).FirstOrDefault();
            edytowany.Tytul = film.Tytul;
            edytowany.Rezyser = film.Rezyser;
            edytowany.Opis = film.Opis;
            edytowany.Cena = film.Cena;
            edytowany.DataDodania = film.DataDodania;

            db.SaveChanges();

            return RedirectToAction("Szczegoly", new { idFilmu = film.Id });
        }
        [HttpPost]
        public IActionResult Szukaj(string fraza)
        {
            var filmy = from f in db.Filmy select f;

            filmy = filmy.Where(f => f.Tytul.ToLower().Contains(fraza.ToLower()));
            ViewBag.szukanie = fraza;

            return View(filmy.ToList());
        }
    }
}

TISklep/Controllers/KoszykController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TISklep.DAL;
using TISklep.Infrastructure;
using TISklep.Models;
using TISklep.ViewModels;

namespace TISklep.Controllers
{
    public class KoszykController : Controller
    {
        FilmyContext db;

        public KoszykController(FilmyContext db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            var cart = CartManager.GetItems(HttpContext.Session);
            ViewBag.total = CartManager.GetCartValue(HttpContext.Session);
            return View(cart);
        }
        public IActionResult DodajDoKoszyka(int IdFilmu)
        {
            CartManager.AddToCart(HttpContext.Session, db, IdFilmu);
            return RedirectToAction("Index");
        }
        public IActionResult UsunZKoszyka(int id)
        {
            var model = new UsuwanieElementuKoszykaViewModel()
            {
                Id = id,
                Ilosc = CartManager.RemoveFromCart(HttpContext.Session, id),
                WartoscKoszyka = CartManager.GetCartValue(HttpContext.Session),
                IloscTotal = CartManager.GetCartQuantity(HttpContext.Session)
            };
            return Json(model);
        }
    }
}

TISklep/ViewComponents/FilmyKategoriiViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TISklep.DAL;

namespace TISklep.ViewComponents
{
    public class FilmyKategoriiViewComponent : ViewComponent
    {
        FilmyContext db;

        public FilmyKategoriiViewComponent(FilmyContext db)
        {
            this.db = db;
        }

        public async Task<IViewComponentResult> InvokeAsync(string nazwaKategorii)
        {
            var kategoria = db.Kategorie.Include("Filmy").Where(k => k.Nazwa == nazwaKategorii).Single();
            var filmy = kategoria.Filmy.ToList();

            return await Task.FromResult((IViewComponentResult)View("_FilmyKategorii", filmy));
        }
    }
}

TISklep/Views/Filmy/DodajFilm.cshtml
@model TISklep.ViewModels.DodawanieFilmowViewModel

@using (Html.BeginForm("DodajFilm", "Filmy", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Film.Tytul, "Podaj tytuł: ")
        @Html.TextBoxFor(m => m.Film.Tytul, new { @required = true, @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Film.Rezyser, "Podaj rezysera: ")
        @Html.TextBoxFor(m => m.Film.Rezyser, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Film.Opis, "Podaj opis: ")
        @Html.TextAreaFor(m => m.Film.Opis, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Film.Cena, "Podaj cene: ")
        @Html.TextBoxFor(m => m.Film.Cena, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Plakat, "Wybierz plakat: ")
        @Html.TextBoxFor(m => m.Plakat, new { @type = "file", @class = "form-control-file" })
    </div>

    <div class="form-check">
        @foreach (var kategoria in Model.Kategorie)
        {
            
                @Html.RadioButtonFor(m => m.Film.KategoriaId, kategoria.Id, new { @class = "form-check-input" })
                @kategoria.Nazwa
            <br/>
        }
    </div>
    <div>
    <input type="submit" value="Dodaj do bazy" class="btn btn-primary" />
    </div>
}

TISklep/Views/Filmy/EdytujFilm.cshtml
@model TISklep.Models.Film
@*<title>@ViewData["Title"] -  Szczegóły</title>*@

@using (Html.BeginForm())
{
    @Html.HiddenFor(f => f.Plakat)
    @Html.HiddenFor(f => f.KategoriaId)

    <table>
        <tr>
            <td>
                <h1>@Model.Kategoria.Nazwa</h1>
                @await Component.InvokeAsync("FilmyKategorii", new { nazwaKategorii = Model.Kategoria.Nazwa })
            </td>
            <td>
                <ul>
                    <li>Tytuł: @Html.TextBoxFor(f => f.Tytul)</li>
                    <li>Reżyser: @Html.TextBoxFor(f => f.Rezyser)</li>
                    <li>Opis: @Html.TextAreaFor(f => f.Opis)</li>
                    <li>Cena: :@Html.TextBoxFor(f => f.Cena) zł</li>
                    <li>Data dodania: @Html.TextBoxFor(f => f.DataDodania, new { @type = "date" })</li>
                </ul>

            </td>
        </tr>
    </table>
    <button type="submit">Zapisz</button>
} 

TISklep/Views/Filmy/ListaFilmow.cshtml
@model TISklep.ViewModels.KategoriaViewModel

<title>@ViewData["Title"] - Lista filmów</title>

<table>
    <tr>
        @foreach (var film in Model.FilmyTop3Najnowsze)
            {
                <td>
                    <h3>@film.Tytul</h3>
                    <p>@film.Opis</p>
                    <img src="~/content/@film.Plakat"/>
                </td>
            }
    </tr>
</table>


<div class="tabele m-5">
    <h1><b>@Model.Kategoria.Nazwa</b></h1>
    <h3>@Model.Kategoria.Opis</h3>
    <table>
        <thead>
            <tr>
                <th class="th25">Tytuł filmu</th>
                <th class="th25">Reżyser</th>
                <th class="th25">Data dodania</th>
                <th class="th25">Cena</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var film in Model.FilmyKategorii)
            {
                <tr>
                    <td>@film.Tytul</td>
                    <td>@film.Rezyser</td>
                    <td>@film.DataDodania.Value.Date.ToString("dd MMMM yyyy")</td>
                    <td>@film.Cena zł</td>
                    <td>
                        <a href="@Url.Action("Szczegoly", "Filmy", new { idFilmu=film.Id })">&#128270;</a>
                    </td>
                    <td>
                        <a href="@Url.Action("DodajDoKoszyka", "Koszyk", new { idFilmu=film.Id })">&#128722;</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

TISklep/Views/Filmy/Szczegoly.cshtml
@model TISklep.Models.Film

    <title>@ViewData["Title"] -  Szczegóły</title>


<table>
    <tr>
        <td>
            <h1>@Model.Kategoria.Nazwa</h1>
            @await Component.InvokeAsync("FilmyKategorii", new { nazwaKategorii = Model.Kategoria.Nazwa })
        </td>
        <td>
            <ul>
                <li>Tytuł: @Model.Tytul</li>
                <li>Reżyser: @Model.Rezyser</li>
                <li>Opis: @Model.Opis</li>
                <li>Cena: @Model.Cena zł</li>
                <li>Data dodania: @Model.DataDodania</li>
            </ul>
            <button onclick="location.href='@Url.Action("EdytujFilm","Filmy", new { id = Model.Id })'">Edytuj</button>
        </td>
    </tr>
</table>

TISklep/Views/Filmy/Szukaj.cshtml
@model IEnumerable<TISklep.Models.Film>

<h3>Filmy zawierające fraze: @ViewBag.szukanie</h3>

<div class="tabele m-5">
    <table>
        <thead>
            <tr>
                <th class="th25">Tytuł filmu</th>
                <th class="th25">Reżyser</th>
                <th class="th25">Data dodania</th>
                <th class="th25">Cena</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var film in Model)
            {
                <tr>
                    <td>@film.Tytul</td>
                    <td>@film.Rezyser</td>
                    <td>@film.DataDodania.Value.Date.ToString("dd MMMM yyyy")</td>
                    <td>@film.Cena zł</td>
                    <td>
                        <a href="@Url.Action("Szczegoly", "Filmy", new { idFilmu=film.Id })">&#128270;</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

TISklep/Views/Filmy/Wszystkie.cshtml
@model IEnumerable<TISklep.Models.Film>
    <div class="wszystkie-filmy">
        <ul>
            @foreach (var film in Model)
            {
                <li class="pojedynczy-film">
                    <a href="@Url.Action("Szczegoly","Filmy", new { idFilmu = film.Id})"> <img src="~/content/@film.Plakat" /></a>
                </li>
            }
        </ul>
    </div>